### ISSUE TITLE
[Meta] dbx_sqlite

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#2619]
- [x] crash under Wine #2323

- [x] Event updates do not work properly #2121

- [x] only the first of unread events is shown when multiple unread events arrive #1985

- [x] SQLite, Scriver и количество последних сообщений #2142

- [x] dbx_sqlite: driver prevents main thread termination #1642
