### ISSUE TITLE
Possible regressions in stable version

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#908]
Meta ticket for tracking all possible regressions:

- [x]  #987
- [ ] Facebook don't login (more info requested) - https://forum.ru-board.com/topic.cgi?forum=5&topic=39486&start=2840#9
- [ ] Multiple problems with IRC (more info requested) - https://forum.ru-board.com/topic.cgi?forum=5&topic=39486&start=2840#9
- [ ] #1014
- [x] cannot reach "Send" button via Tab - https://forum.miranda-ng.org/index.php?topic=5266.msg20308#msg20308
- [x] Crash - https://forum.miranda-ng.org/index.php?topic=4463.msg20291#msg20291
- [x] Missing icons in GmailMultipleNotifier - https://forum.miranda-ng.org/index.php?topic=2300.msg20298#msg20298
- [x] #915
- [ ] #912 (more info requested)
- [x] #934
- [x] #967
- [x] #973
- [ ] #995

**Comment by kotkotofey** [comment]
Send files via Jabber to users with older versions MirandaNG (v.0.95.5 and earlier) not working.  I got message "no compatible file transfer mechanism exists".  Also noticed that at the monemt of the file transfer nothing is written to netlog.txt

**Comment by dartraiden** [comment]
Scriver regression is moved to #1014. All other bugs are not confirmed. So close this meta-ticket.

**Comment by dergilb99** [comment]
> All other bugs are not confirmed.

@georgehazan confirmed it.
